#!/bin/sh

echo "Running pre-push hook"

BIN_PATH="$(git rev-parse --show-toplevel)/node_modules/.bin"
SRC_PATH="$(git rev-parse --show-toplevel)/src"

jest() {
	JEST="$BIN_PATH/jest"
	   
	# Check for jest
	if [[ ! -x "$JEST"  ]]; then
		printf "\t\033[41mPlease install Jest\033[0m\n"
		exit 1
	fi
				
	echo "Running tests"
				
	$JEST $SRC_PATH --bail --silent
		
	if [[ $? == 0  ]]; then
		printf "\n\033[1;32mTest Passed\033[0m\n"
	else
		printf "\n\033[41mTest Failed:\033[0m Fix test errors and try again!\n"
		exit 1
	fi
}

jest

exit $?
